//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:24:01 AM GMT+03:00 
//


package com.ipeirotis.mturk.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnswerSpecificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnswerSpecificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="FreeTextAnswer" type="{http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd}FreeTextAnswerType"/>
 *         &lt;element name="SelectionAnswer" type="{http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd}SelectionAnswerType"/>
 *         &lt;element name="FileUploadAnswer" type="{http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd}FileUploadAnswerType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnswerSpecificationType", namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", propOrder = {
    "freeTextAnswer",
    "selectionAnswer",
    "fileUploadAnswer"
})
public class AnswerSpecificationType {

    @XmlElement(name = "FreeTextAnswer", namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd")
    protected FreeTextAnswerType freeTextAnswer;
    @XmlElement(name = "SelectionAnswer", namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd")
    protected SelectionAnswerType selectionAnswer;
    @XmlElement(name = "FileUploadAnswer", namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd")
    protected FileUploadAnswerType fileUploadAnswer;

    /**
     * Gets the value of the freeTextAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextAnswerType }
     *     
     */
    public FreeTextAnswerType getFreeTextAnswer() {
        return freeTextAnswer;
    }

    /**
     * Sets the value of the freeTextAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextAnswerType }
     *     
     */
    public void setFreeTextAnswer(FreeTextAnswerType value) {
        this.freeTextAnswer = value;
    }

    /**
     * Gets the value of the selectionAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link SelectionAnswerType }
     *     
     */
    public SelectionAnswerType getSelectionAnswer() {
        return selectionAnswer;
    }

    /**
     * Sets the value of the selectionAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectionAnswerType }
     *     
     */
    public void setSelectionAnswer(SelectionAnswerType value) {
        this.selectionAnswer = value;
    }

    /**
     * Gets the value of the fileUploadAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link FileUploadAnswerType }
     *     
     */
    public FileUploadAnswerType getFileUploadAnswer() {
        return fileUploadAnswer;
    }

    /**
     * Sets the value of the fileUploadAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileUploadAnswerType }
     *     
     */
    public void setFileUploadAnswer(FileUploadAnswerType value) {
        this.fileUploadAnswer = value;
    }

}
