//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:24:01 AM GMT+03:00 
//


package com.ipeirotis.mturk.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileUploadAnswerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileUploadAnswerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaxFileSizeInBytes" type="{http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd}MaxFileSizeType"/>
 *         &lt;element name="MinFileSizeInBytes" type="{http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd}MinFileSizeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileUploadAnswerType", namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", propOrder = {
    "maxFileSizeInBytes",
    "minFileSizeInBytes"
})
public class FileUploadAnswerType {

    @XmlElement(name = "MaxFileSizeInBytes", namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd")
    protected int maxFileSizeInBytes;
    @XmlElement(name = "MinFileSizeInBytes", namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd")
    protected int minFileSizeInBytes;

    /**
     * Gets the value of the maxFileSizeInBytes property.
     * 
     */
    public int getMaxFileSizeInBytes() {
        return maxFileSizeInBytes;
    }

    /**
     * Sets the value of the maxFileSizeInBytes property.
     * 
     */
    public void setMaxFileSizeInBytes(int value) {
        this.maxFileSizeInBytes = value;
    }

    /**
     * Gets the value of the minFileSizeInBytes property.
     * 
     */
    public int getMinFileSizeInBytes() {
        return minFileSizeInBytes;
    }

    /**
     * Sets the value of the minFileSizeInBytes property.
     * 
     */
    public void setMinFileSizeInBytes(int value) {
        this.minFileSizeInBytes = value;
    }

}
