//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 07:51:40 PM GMT+03:00 
//


package com.ipeirotis.mturk.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ipeirotis.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContentTypeList_QNAME = new QName("http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", "List");
    private final static QName _ContentTypeTitle_QNAME = new QName("http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", "Title");
    private final static QName _ContentTypeBinary_QNAME = new QName("http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", "Binary");
    private final static QName _ContentTypeEmbeddedBinary_QNAME = new QName("http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", "EmbeddedBinary");
    private final static QName _ContentTypeApplication_QNAME = new QName("http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", "Application");
    private final static QName _ContentTypeFormattedContent_QNAME = new QName("http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", "FormattedContent");
    private final static QName _ContentTypeText_QNAME = new QName("http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", "Text");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ipeirotis.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QuestionForm }
     * 
     */
    public QuestionForm createQuestionForm() {
        return new QuestionForm();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link Question }
     * 
     */
    public Question createQuestion() {
        return new Question();
    }

    /**
     * Create an instance of {@link EmbeddedBinaryContentType }
     * 
     */
    public EmbeddedBinaryContentType createEmbeddedBinaryContentType() {
        return new EmbeddedBinaryContentType();
    }

    /**
     * Create an instance of {@link MimeType }
     * 
     */
    public MimeType createMimeType() {
        return new MimeType();
    }

    /**
     * Create an instance of {@link BinaryContentType }
     * 
     */
    public BinaryContentType createBinaryContentType() {
        return new BinaryContentType();
    }

    /**
     * Create an instance of {@link JavaAppletContentType }
     * 
     */
    public JavaAppletContentType createJavaAppletContentType() {
        return new JavaAppletContentType();
    }

    /**
     * Create an instance of {@link EmbeddedMimeType }
     * 
     */
    public EmbeddedMimeType createEmbeddedMimeType() {
        return new EmbeddedMimeType();
    }

    /**
     * Create an instance of {@link ApplicationParameter }
     * 
     */
    public ApplicationParameter createApplicationParameter() {
        return new ApplicationParameter();
    }

    /**
     * Create an instance of {@link SelectionAnswerType }
     * 
     */
    public SelectionAnswerType createSelectionAnswerType() {
        return new SelectionAnswerType();
    }

    /**
     * Create an instance of {@link AnswerSpecificationType }
     * 
     */
    public AnswerSpecificationType createAnswerSpecificationType() {
        return new AnswerSpecificationType();
    }

    /**
     * Create an instance of {@link FlashContentType }
     * 
     */
    public FlashContentType createFlashContentType() {
        return new FlashContentType();
    }

    /**
     * Create an instance of {@link FileUploadAnswerType }
     * 
     */
    public FileUploadAnswerType createFileUploadAnswerType() {
        return new FileUploadAnswerType();
    }

    /**
     * Create an instance of {@link ApplicationContentType }
     * 
     */
    public ApplicationContentType createApplicationContentType() {
        return new ApplicationContentType();
    }

    /**
     * Create an instance of {@link FreeTextAnswerType }
     * 
     */
    public FreeTextAnswerType createFreeTextAnswerType() {
        return new FreeTextAnswerType();
    }

    /**
     * Create an instance of {@link Constraints }
     * 
     */
    public Constraints createConstraints() {
        return new Constraints();
    }

    /**
     * Create an instance of {@link IsNumeric }
     * 
     */
    public IsNumeric createIsNumeric() {
        return new IsNumeric();
    }

    /**
     * Create an instance of {@link Length }
     * 
     */
    public Length createLength() {
        return new Length();
    }

    /**
     * Create an instance of {@link AnswerFormatRegex }
     * 
     */
    public AnswerFormatRegex createAnswerFormatRegex() {
        return new AnswerFormatRegex();
    }

    /**
     * Create an instance of {@link Selections }
     * 
     */
    public Selections createSelections() {
        return new Selections();
    }

    /**
     * Create an instance of {@link Selection }
     * 
     */
    public Selection createSelection() {
        return new Selection();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link HTMLQuestion }
     *
     */
    public HTMLQuestion createHTMLQuestion() {
        return new HTMLQuestion();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", name = "List", scope = ContentType.class)
    public JAXBElement<List> createContentTypeList(List value) {
        return new JAXBElement<List>(_ContentTypeList_QNAME, List.class, ContentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", name = "Title", scope = ContentType.class)
    public JAXBElement<String> createContentTypeTitle(String value) {
        return new JAXBElement<String>(_ContentTypeTitle_QNAME, String.class, ContentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BinaryContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", name = "Binary", scope = ContentType.class)
    public JAXBElement<BinaryContentType> createContentTypeBinary(BinaryContentType value) {
        return new JAXBElement<BinaryContentType>(_ContentTypeBinary_QNAME, BinaryContentType.class, ContentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmbeddedBinaryContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", name = "EmbeddedBinary", scope = ContentType.class)
    public JAXBElement<EmbeddedBinaryContentType> createContentTypeEmbeddedBinary(EmbeddedBinaryContentType value) {
        return new JAXBElement<EmbeddedBinaryContentType>(_ContentTypeEmbeddedBinary_QNAME, EmbeddedBinaryContentType.class, ContentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", name = "Application", scope = ContentType.class)
    public JAXBElement<ApplicationContentType> createContentTypeApplication(ApplicationContentType value) {
        return new JAXBElement<ApplicationContentType>(_ContentTypeApplication_QNAME, ApplicationContentType.class, ContentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", name = "FormattedContent", scope = ContentType.class)
    public JAXBElement<String> createContentTypeFormattedContent(String value) {
        return new JAXBElement<String>(_ContentTypeFormattedContent_QNAME, String.class, ContentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionForm.xsd", name = "Text", scope = ContentType.class)
    public JAXBElement<String> createContentTypeText(String value) {
        return new JAXBElement<String>(_ContentTypeText_QNAME, String.class, ContentType.class, value);
    }

}
